{
    "name": "Community IoT ZPL",
    "summary": "Send Zebra ZPL labels through Community IoT.",
    "description": "Create bounded ZPL jobs for compatible Community IoT label printers.",
    "version": "18.0.1.0.0",
    "category": "Inventory/Inventory",
    "author": "JDA SOLUTIONS",
    "maintainer": "JDA SOLUTIONS",
    "website": "https://github.com/julesprog963-stack/community_iot_integrations",
    "support": "julesprog963@gmail.com",
    "license": "LGPL-3",
    "price": 0.0,
    "currency": "USD",
    "images": ["static/description/main_screenshot.png", "static/description/images/jda-solutions-logo.png"],
    "depends": ["base", "web", "product", "stock", "community_iot_box"],
    "data": [
        "security/community_iot_zpl_security.xml",
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/community_iot_zpl_views.xml",
        "wizard/community_iot_zpl_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
}
